"use client"
import Mosque from "@/Components/Mosque/index.jsx";

const MosquePage = ({ params }) => {
    const datas = [
        {
            id: 1,
            gotoPlace: [34.60748058006762, 50.90726031582144],
            title: "مسجد جامع قم",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 24,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 2,
            gotoPlace: [34.60073886290321, 50.8697674489971],
            title: "مسجد حضرت زینب",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 2,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 3,
            gotoPlace: [35.793685522439645, 51.44145317157504],
            title: "مسجد کربلا",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 5,
            meets: 15,
            accupy: "خانوادگی",
            step: "قانون کار"
        },
        {
            id: 4,
            gotoPlace: [35.78238878440862, 51.454560182899556],
            title: "مسجد هدایت",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 23,
            accupy: "گروهی",
            step: "توافقی"
        },
        {
            id: 5,
            gotoPlace: [35.774413649690054, 51.48323177017192],
            title: "مسجد مبارک آباد",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 8,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 6,
            gotoPlace: [35.76370405024132, 51.43731199109132],
            title: "مسجد الغدیر",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 2,
            meets: 36,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 7,
            gotoPlace: [35.749017066382905, 51.46207816564519],
            title: "مسجد الرقیه",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 28,
            accupy: "گروهی",
            step: "توافقی"
        },
        {
            id: 8,
            gotoPlace: [35.74109269944609, 51.43183485633422],
            title: "مسجد الرضا",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 5,
            meets: 14,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 9,
            gotoPlace: [35.72272833015019, 51.4711273448091],
            title: "مسجد الفاطمیه",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 18,
            accupy: "گروهی",
            step: "توافقی"
        },
        {
            id: 10,
            gotoPlace: [35.70919398019333, 51.453743395362636],
            title: "مسجد امام کاظم",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 27,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 11,
            gotoPlace: [35.721374998597256, 51.4156415883567],
            title: "مسجد نور",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 5,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 12,
            gotoPlace: [35.70977407090814, 51.47065107222152],
            title: "مسجد صفا",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 65,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 13,
            gotoPlace: [35.69372333720725, 51.46993666334016],
            title: "مسجد حضرت محمد",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 3,
            accupy: "گروهی",
            step: "توافقی"
        },
        {
            id: 14,
            gotoPlace: [35.676508719827616, 51.439455217735414],
            title: "مسجد جامع تهران",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 48,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 15,
            gotoPlace: [35.701072266917606, 51.37611096358804],
            title: "مسجد حضرت علی",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 14,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 16,
            gotoPlace: [35.76640925157217, 51.38349318869544],
            title: "مسجد الزهرا",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 65,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 17,
            gotoPlace: [35.75694064442707, 51.37825419023213],
            title: "مسجد جامع شهرک غرب",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 56,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 18,
            gotoPlace: [35.77848754727574, 51.35550040157627],
            title: "مسجد باقر العلوم",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 3,
            meets: 89,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 19,
            gotoPlace: [35.74836149324854, 51.33593897540092],
            title: "مسجد جامع باغ فیض",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 25,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        {
            id: 20,
            gotoPlace: [35.73134981229993, 51.34352401820361],
            title: "مسجد جامع امام سجاد",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 2,
            meets: 204,
            accupy: "مجردی",
            step: "توافقی"
        },
        {
            id: 21,
            gotoPlace: [35.65771592562385, 51.364740706976335],
            title: "مسجد البرز",
            address: "قم، خیابان جمهوری، بلوار شهید ابراهیمی، کوچه  ۱۱",
            images: [
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
                { img: "/images/slider/slide-2.jpg" },
                { img: "/images/slider/slide-3.jpg" },
                { img: "/images/slider/slide-4.jpg" },
                { img: "/images/slider/slide-1.jpg" },
            ],
            score: 4,
            meets: 24,
            accupy: "خانوادگی",
            step: "توافقی"
        },
        /* End Mosques */
    ];

    const location = datas.find((data) => data.id == params.slug);

    return (
        <div>
            <Mosque location={location}/>
        </div>
    );
}

export default MosquePage;